Models/Expediente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace XMedicalLite.Models
{
    public class Expediente
    {
        public int ExpedienteID { get; set; }
        public int PacienteID { get; set; }
        public int TriajeID { get; set; }

        [Display(Name = "Motivo de consulta")]
        [DataType(DataType.MultilineText)]
        public string MotivoConsulta { get; set; }

        //Anamnesis
        [Display(Name = "Antecedentes")]
        [DataType(DataType.MultilineText)]
        public string Antecedentes { get; set; }

        [Display(Name = "Historia de enfermedad actual")]
        [DataType(DataType.MultilineText)]
        public string HistoriaEnfermedad { get; set; }

        //Signos vitales
        //public int Pulso { get; set; }

        [Display(Name = "Frecuencia cardiaca (L/Min)")]
        public int FrecuenciaCardiaca { get; set; }

        //[RegularExpression("^\d\d\d/\d(1,2)")]
        [Display(Name = "Presion arterial (Mm/Hg)")]
        public string PrecionArteriar { get; set; }

        [Display(Name = "Frecuencia respiratoria (R/Min)")]
        public int FrecuenciaRespiratoria { get; set; }

        [Display(Name = "Temperatura (Celcius)")]
        public float Temperatura { get; set; }

        [Display(Name ="Peso (Lb)")]
        public float Peso { get; set; }

        [Display(Name ="Saturacion O2 (%)")]
        public int SaturacionOxigeno { get; set; }

        [Display(Name ="Escala de Glasgow")]
        public int EscalaGlasgow { get; set; }

        [Display(Name ="Escala de dolor")]
        public int EscalaDolor { get; set; }

        //Examen general
        [Display(Name = "Examen fisico")]
        [DataType(DataType.MultilineText)]
        public string ExamenFisico { get; set; }

        [Display(Name = "Diagnostico")]
        public string Diagnostico { get; set; }

        [Display(Name = "Estudios de imagenes y analiticas")]
        [DataType(DataType.MultilineText)]
        public string Estudio { get; set; }

        [Display(Name = "Tratamientos")]
        [DataType(DataType.MultilineText)]
        public string Tratramiento { get; set; }

        [Display(Name = "Notas")]
        [DataType(DataType.MultilineText)]
        public string Nota { get; set; }

        [Display(Name = "Destino")]
        public string Destino { get; set; }

        [Display(Name = "Nombre del medico")]
        public string NombreMedico { get; set; }

        [Display(Name = "Fecha creado")]
        [DataType(DataType.DateTime)]
        public DateTime CreadoEn { get; set; }

        [Display(Name = "Fecha actualizado")]
        [DataType(DataType.DateTime)]
        public DateTime ActualizadoEn { get; set; }

        public Expediente()
        {
            this.CreadoEn = DateTime.Now;
            this.ActualizadoEn = DateTime.Now;
        }

        public virtual Paciente Paciente { get; set; }
        public virtual Triaje Triaje { get; set; }

        //Salida del paciente

    }
}

Controllers/ExpedientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XMedicalLite.Models;

namespace XMedicalLite_Windows.Controllers
{
    public class ExpedientesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Expedientes
        public ActionResult Index()
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var expedientes = db.Expedientes.Include(p => p.Paciente);
            return View(expedientes);
        }

        // GET: Expedientes/Details/5
        public ActionResult Details(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            return View(expediente);
        }

        // GET: Expedientes/Create
        public ActionResult Create(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.PacienteID = id;
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color");
            return View();
        }

        // POST: Expedientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Expediente expediente, int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            expediente.PacienteID = id;
            try
            {
                db.Expedientes.Add(expediente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.PacienteID = id;
                ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
                return View(expediente);
            }
        }

        // GET: Expedientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            ViewBag.PacienteID = new SelectList(db.Pacientes, "PacienteID", "Nombres", expediente.PacienteID);
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
            return View(expediente);
        }

        // POST: Expedientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Expediente expediente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                expediente.ActualizadoEn = DateTime.Now;
                db.Entry(expediente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PacienteID = new SelectList(db.Pacientes, "PacienteID", "Nombres", expediente.PacienteID);
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
            return View(expediente);
        }

        // GET: Expedientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            return View(expediente);
        }

        // POST: Expedientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            Expediente expediente = db.Expedientes.Find(id);
            db.Expedientes.Remove(expediente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //METODOS AUXILIARES
       
    }
}

Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XMedicalLite.Models;

namespace XMedicalLite_Windows.Controllers
{
    public class PacientesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Pacientes
        public ActionResult Index(string busqueda)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            if(string.IsNullOrEmpty(busqueda))
            {
                return View(db.Pacientes.ToList());
            }
            var pacientes = db.Pacientes.Where(p => p.Nombres.Contains(busqueda) || p.Apellidos.Contains(busqueda) || p.Cedula.Contains(busqueda));
            
            return View(pacientes.ToList());
        }

        // GET: Pacientes/Details/5
        public ActionResult Details(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // GET: Pacientes/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.SexoId = new SelectList(db.Sexos, "SexoID", "Descripcion");
            ViewBag.EstadoCivilId = new SelectList(db.EstadosCivil, "EstadoCivilID", "Descripcion");
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Paciente paciente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Pacientes.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            paciente.FechaNacimiento = paciente.FechaNacimiento.Date;
            if (paciente == null)
            {
                return HttpNotFound();
            }
            ViewBag.SexoId = new SelectList(db.Sexos, "SexoID", "Descripcion", paciente.SexoID);
            ViewBag.EstadoCivilId = new SelectList(db.EstadosCivil, "EstadoCivilID", "Descripcion", paciente.EstadoCivilID);
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Paciente paciente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            Paciente paciente = db.Pacientes.Find(id);
            db.Pacientes.Remove(paciente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DatosPaciente(int idPaciente, int idExpediente = 0)
        {
            DateTime fechaCreado = DateTime.Now;
            if(idExpediente != 0)
            {
                fechaCreado = db.Expedientes.Find(idExpediente).CreadoEn;
            }
            ViewBag.fechaCreado = fechaCreado.ToString("G", CultureInfo.CreateSpecificCulture("es-DO"));
            var paciente = db.Pacientes.Find(idPaciente);
            return PartialView("/Views/Shared/_Paciente.cshtml", paciente);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ReportesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using XMedicalLite.Models;
using XMedicalLite_Windows.Models;
using XMedicalLite_Windows.Tools;

namespace XMedicalLite_Windows.Controllers
{
    public class ReportesController : Controller
    {
        MyDbContext db = new MyDbContext();
        // GET: Reportes
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Reporte(int id)
        {
            Reporte reporte = new Reporte();
            reporte.Expediente = db.Expedientes.Find(id);
            reporte.Paciente = db.Pacientes.Find(reporte.Expediente.PacienteID);
            reporte.Empresa = db.Empresas.FirstOrDefault();
            //ViewBag.edad = DateTime.Now.Year - reporte.Paciente.FechaNacimiento.Year;
            ViewBag.edad = new Utility().Age(reporte.Paciente.FechaNacimiento, reporte.Expediente.CreadoEn);
            return View(reporte);
        }

    }
}

Views/Expedientes/Create.cshtml
@model XMedicalLite.Models.Expediente

@{
    ViewBag.Title = "Create";
}

@*<div class="">
    <strong>
        @Html.LabelFor(model => model.FechaCreado)
    </strong>
    @Html.DisplayFor(model => model.FechaCreado)
</div>*@

<div class="">
    @{Html.RenderAction("DatosPaciente", "Pacientes", new { idPaciente = ViewBag.PacienteID }); }
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="row">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PacienteID, htmlAttributes: new { })

        <div class="row">
            <div class="col">
                @Html.LabelFor(model => model.Triaje.Color)
                @Html.DropDownListFor(model => model.TriajeID, ViewBag.TriajeID as SelectList, "Seleccionar", htmlAttributes: new { @class="form-group"})
            </div>
        </div>

        <div class="col-12 mt-3">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.MotivoConsulta, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.MotivoConsulta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MotivoConsulta, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.HistoriaEnfermedad, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.HistoriaEnfermedad, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.HistoriaEnfermedad, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.Antecedentes, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.Antecedentes, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Antecedentes, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.ExamenFisico, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.ExamenFisico, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ExamenFisico, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>Signos vitales</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.FrecuenciaCardiaca, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.FrecuenciaCardiaca, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FrecuenciaCardiaca, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.PrecionArteriar, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.PrecionArteriar, new { htmlAttributes = new { @class = "form-control", @id = "precionArteriar" } })
                            @Html.ValidationMessageFor(model => model.PrecionArteriar, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.FrecuenciaRespiratoria, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.FrecuenciaRespiratoria, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.FrecuenciaRespiratoria, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.Temperatura, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.Temperatura, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Temperatura, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>Otros parametros</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.Peso, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.Peso, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Peso, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.SaturacionOxigeno, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.SaturacionOxigeno, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SaturacionOxigeno, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.EscalaGlasgow, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.EscalaGlasgow, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EscalaGlasgow, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-3">
                            @Html.LabelFor(model => model.EscalaDolor, htmlAttributes: new { @class = "" })
                            @Html.EditorFor(model => model.EscalaDolor, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.EscalaDolor, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.Diagnostico, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.Diagnostico, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Diagnostico, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.Tratramiento, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.Tratramiento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Tratramiento, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.Estudio, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.Estudio, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Estudio, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                <div class="card-header">
                    <h4>@Html.LabelFor(model => model.Nota, htmlAttributes: new { @class = "" })</h4>
                </div>
                <div class="card-body">
                    @Html.EditorFor(model => model.Nota, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Nota, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-12 mt-2">
            <div class="card">
                @*<div class="card-header">
                        <h4></h4>
                    </div>*@
                <div class="card-body">
                    <div class="row">
                        <div class="form-group col-5">
                            <h5>@Html.LabelFor(model => model.Destino, htmlAttributes: new { @class = "" })</h5>
                            @Html.EditorFor(model => model.Destino, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Destino, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group col-5 offset-2">
                            <h5>@Html.LabelFor(model => model.NombreMedico, htmlAttributes: new { @class = "" })</h5>
                            @Html.EditorFor(model => model.NombreMedico, new { htmlAttributes = new { @class = "form-control align-right" } })
                            @Html.ValidationMessageFor(model => model.NombreMedico, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="form-group mt-2 offset-10">
            @Html.ActionLink("Cancelar", "Index", null, htmlAttributes: new { @class = "btn btn-danger" })
            <input type="submit" value="Guardar" class="btn btn-primary" />
        </div>
    </div>
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/site.js"></script>

@*<script>
        $(document).ready(function () {
            $("#precionArteriar").mask("000/000");
        })
    </script>*@

Views/Expedientes/Details.cshtml
@model XMedicalLite.Models.Expediente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Expediente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Paciente.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Paciente.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aseguradora)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aseguradora)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumeroNSS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroNSS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MotivoIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MotivoIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Antecedentes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Antecedentes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrecuenciaCardiaca)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrecuenciaCardiaca)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PrecionArteriar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PrecionArteriar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FrecuenciaRespiratoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FrecuenciaRespiratoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ExamenPaciente)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ExamenPaciente)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Diagnostico)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Diagnostico)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Conducta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Conducta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Evolucion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evolucion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Recomendacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Recomendacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ExpedienteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Expedientes/Index.cshtml
@model IEnumerable<XMedicalLite.Models.Expediente>

@{
    ViewBag.Title = "Index";
    int cont = 0;
}

<table class="table">
    <tr>
        <th>
            No.
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paciente.Referencia)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paciente.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paciente.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Paciente.Cedula)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreadoEn)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.Referencia)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Paciente.Cedula)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CreadoEn)
        </td>
        
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.ExpedienteID }, htmlAttributes: new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Imprimir", "Reporte", "Reportes", new { id=item.ExpedienteID}, htmlAttributes: new { @class = "btn btn-primary", @target="_blank" })
        </td>
    </tr>
}

</table>