Models/Paciente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace XMedicalLite.Models
{
    public class Paciente
    {
        public int PacienteID { get; set; }

        [Display(Name ="Numero de Referencia")]
        public string Referencia { get; set; }

        [Display(Name ="Nombres")]
        public string Nombres { get; set; }

        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }

        [Display(Name = "Sexo")]
        public int SexoID { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Display(Name = "Cedula")]
        public string Cedula { get; set; }

        [Display(Name = "Estado civil")]
        public int EstadoCivilID { get; set; }

        [Display(Name = "Telefono")]
        public string Telefono { get; set; }

        [Display(Name = "Direccion")]
        public string Direccion { get; set; }

        [Display(Name = "Provincia")]
        public string Provincia { get; set; }

        [Display(Name = "Municipio")]
        public string Municipio { get; set; }

        [Display(Name = "Aseguradora")]
        public string Aseguradora { get; set; }

        [Display(Name = "Numero de NSS/Poliza")]
        public string NumeroNSS { get; set; }


        public virtual Sexo Sexo { get; set; }
        public virtual EstadoCivil EstadoCivil { get; set; }
    }
}

Controllers/ExpedientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XMedicalLite.Models;

namespace XMedicalLite_Windows.Controllers
{
    public class ExpedientesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Expedientes
        public ActionResult Index()
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            var expedientes = db.Expedientes.Include(p => p.Paciente);
            return View(expedientes);
        }

        // GET: Expedientes/Details/5
        public ActionResult Details(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            return View(expediente);
        }

        // GET: Expedientes/Create
        public ActionResult Create(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.PacienteID = id;
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color");
            return View();
        }

        // POST: Expedientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Expediente expediente, int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            expediente.PacienteID = id;
            try
            {
                db.Expedientes.Add(expediente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                ViewBag.PacienteID = id;
                ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
                return View(expediente);
            }
        }

        // GET: Expedientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            ViewBag.PacienteID = new SelectList(db.Pacientes, "PacienteID", "Nombres", expediente.PacienteID);
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
            return View(expediente);
        }

        // POST: Expedientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Expediente expediente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                expediente.ActualizadoEn = DateTime.Now;
                db.Entry(expediente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PacienteID = new SelectList(db.Pacientes, "PacienteID", "Nombres", expediente.PacienteID);
            ViewBag.TriajeID = new SelectList(db.Triajes, "TriajeID", "Color", expediente.TriajeID);
            return View(expediente);
        }

        // GET: Expedientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Expediente expediente = db.Expedientes.Find(id);
            if (expediente == null)
            {
                return HttpNotFound();
            }
            return View(expediente);
        }

        // POST: Expedientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            Expediente expediente = db.Expedientes.Find(id);
            db.Expedientes.Remove(expediente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //METODOS AUXILIARES
       
    }
}

Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using XMedicalLite.Models;

namespace XMedicalLite_Windows.Controllers
{
    public class PacientesController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: Pacientes
        public ActionResult Index(string busqueda)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            if(string.IsNullOrEmpty(busqueda))
            {
                return View(db.Pacientes.ToList());
            }
            var pacientes = db.Pacientes.Where(p => p.Nombres.Contains(busqueda) || p.Apellidos.Contains(busqueda) || p.Cedula.Contains(busqueda));
            
            return View(pacientes.ToList());
        }

        // GET: Pacientes/Details/5
        public ActionResult Details(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // GET: Pacientes/Create
        public ActionResult Create()
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            ViewBag.SexoId = new SelectList(db.Sexos, "SexoID", "Descripcion");
            ViewBag.EstadoCivilId = new SelectList(db.EstadosCivil, "EstadoCivilID", "Descripcion");
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Paciente paciente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Pacientes.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            paciente.FechaNacimiento = paciente.FechaNacimiento.Date;
            if (paciente == null)
            {
                return HttpNotFound();
            }
            ViewBag.SexoId = new SelectList(db.Sexos, "SexoID", "Descripcion", paciente.SexoID);
            ViewBag.EstadoCivilId = new SelectList(db.EstadosCivil, "EstadoCivilID", "Descripcion", paciente.EstadoCivilID);
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Paciente paciente)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Pacientes.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (HttpContext.Session.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            Paciente paciente = db.Pacientes.Find(id);
            db.Pacientes.Remove(paciente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DatosPaciente(int idPaciente, int idExpediente = 0)
        {
            DateTime fechaCreado = DateTime.Now;
            if(idExpediente != 0)
            {
                fechaCreado = db.Expedientes.Find(idExpediente).CreadoEn;
            }
            ViewBag.fechaCreado = fechaCreado.ToString("G", CultureInfo.CreateSpecificCulture("es-DO"));
            var paciente = db.Pacientes.Find(idPaciente);
            return PartialView("/Views/Shared/_Paciente.cshtml", paciente);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Pacientes/Create.cshtml
@model XMedicalLite.Models.Paciente

@{
    ViewBag.Title = "Create";
}

@*<h2>Create</h2>*@


<h4>Paciente nuevo</h4>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Referencia, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Referencia, new { htmlahtmlAttributes = new { @class = "form-control" } })
        </div>
    </div>

    <div class="row">

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Sexo.Descripcion, htmlAttributes: new { @class = "" })
            @Html.DropDownListFor(model => model.SexoID, ViewBag.SexoId as SelectList, "Seleccionar", new { htmlAttributes = new { @class = "form-control text-box single-line", @required = "required" } })
            @Html.ValidationMessageFor(model => model.SexoID, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.FechaNacimiento, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.FechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FechaNacimiento, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.EstadoCivil.Descripcion, htmlAttributes: new { @class = "" })
            @Html.DropDownListFor(model => model.EstadoCivilID, ViewBag.EstadoCivilId as SelectList, "Seleccionar", new { htmlAttributes = new { @class = "form-control text-box single-line", @required = "required" } })
            @Html.ValidationMessageFor(model => model.EstadoCivilID, "", new { @class = "text-danger" })
        </div>


        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
        </div>



        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Provincia, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Provincia, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
            @Html.ValidationMessageFor(model => model.Provincia, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-md-4">
            @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Municipio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Municipio, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-3">
            @Html.LabelFor(model => model.Aseguradora, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.Aseguradora, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Aseguradora, "", new { @class = "text-danger" })
        </div>

        <div class="form-group col-3">
            @Html.LabelFor(model => model.NumeroNSS, htmlAttributes: new { @class = "" })
            @Html.EditorFor(model => model.NumeroNSS, new { htmlAttributes = new { @class = "form-control", @type = "number" } })
            @Html.ValidationMessageFor(model => model.NumeroNSS, "", new { @class = "text-danger" })
        </div>

        <div class="form-group offset-10">
            @Html.ActionLink("Cancelar", "Index", null, htmlAttributes: new { @class = "btn btn-danger" })
            <input type="submit" value="Registrar" class="btn btn-primary" />
        </div>

        <div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Views/Pacientes/Delete.cshtml
@model XMedicalLite.Models.Paciente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provincia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provincia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Municipio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Pacientes/Details.cshtml
@model XMedicalLite.Models.Paciente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Provincia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Provincia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Municipio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Municipio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PacienteID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Pacientes/Index.cshtml
@model IEnumerable<XMedicalLite.Models.Paciente>

@{
    ViewBag.Title = "Index";
}

<div class="mt-2">
    <p>
        @Html.ActionLink("Nuevo paciente", "Create", null, new { @class = "btn btn-primary" })
    </p>
</div>

<div>
    <form action="/Pacientes/Index" method="get">
        <input type="text" name="busqueda"/>
        <input type="submit" value="Buscar" />
    </form>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellidos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cedula)
        </th>
       
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaNacimiento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cedula)
        </td>
        
        <td>
            @Html.ActionLink("Abrir expediente", "Create", "Expedientes", new { id = item.PacienteID }, htmlAttributes: new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.PacienteID }, htmlAttributes: new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PacienteID }, htmlAttributes: new { @class = "btn btn-primary" })
        </td>
    </tr>
}

</table>